### PR TITLE
Fix compatibility with PHP 7.3

### PR DESCRIPTION
**Pull request by felixonmars**
The regex fails to parse in PHP 7.3, which broke the page in later functions.

```
PHP Warning:  preg_replace(): Compilation failed: invalid range in character class at offset 4 in /var/www/felixcat/wp-content/plugins/crayon-syntax-highlighter/crayon_langs.class.php on line 340
```

### CODE REVIEW

**Comment by willstocks** [comment]
@felixonmars - don't suppose you have Crayon working with WP 5.0?

**Comment by felixonmars** [comment]
Indeed, I am running Crayon with WP 5.0 under PHP 7.3.

**Comment by willstocks** [comment]
Interesting!

I’m still on PHP 7.2 at the mo but running WP 5.0!

How are declaring language options in the blocks? I only realised through
fiddling this evening that when I add a code block, it is formatted by
Crayon on the front-end, but I’ve not yet found a way to declare which
language I’m writing!

**Comment by felixonmars** [comment]
I've been using `<pre lang="python">` or `<pre class="lang:python">` for that.

**Comment by willstocks** [comment]
Brilliant! Are you just wrapping it manually by "Edit block as HTML"?

**Comment by felixonmars** [comment]
Yes.

**Comment by bollwarm** [comment]
perfect ,!

**Review by tiefpunkt — APPROVED** [review]

**Comment by gilvegliach** [comment]
Is this ever gonna be released? I spent a lot of time today to figure out the same issue before finding this.
